<?php

$helper = Mage::helper('tealium_tags');
$store = Mage::app()->getStore();

if (!$helper->isEnabled($store)) {
    return; // not enabled, no javascript inserted
}

$terms = array();

if( sizeof($this->getTerms()) > 0 ) {
    foreach ($this->getTerms() as $_term) {
        $terms[] = $_term->getName();
    }
} else {
    $terms[] = "no-terms";
}
?>

<!-- Tealium Popular Search terms page javascript -->
<script type="text/javascript">
    var utag_data={
        site_region: "<?php echo Mage::app()->getLocale()->getLocaleCode(); ?>",
        site_currency: "<?php echo $store->getCurrentCurrencyCode(); ?>",
        page_name: "<?php echo $this->getLayout()->getBlock('head')->getTitle(); ?>",
        page_type: "popular search terms",
        search_keyword: ["<?php echo implode('","', $terms) ?>"]
    };
</script>
