<?php

$helper = Mage::helper('tealium_tags');
$store = Mage::app()->getStore();

if (!$helper->isEnabled($store)) {
    return; // not enabled, no javascript inserted
}

$_product = $this->getProduct();
$_category = Mage::registry('current_category');


?>

<!-- Tealium Product javascript -->
<script type="text/javascript">
    var utag_data={
            site_region: "<?php echo Mage::app()->getLocale()->getLocaleCode(); ?>",
            site_currency: "<?php echo $store->getCurrentCurrencyCode(); ?>",
            page_name: "<?php echo $_product->getName(); ?>",
            page_type: "product",
            product_id: ["<?php echo $_product->getId(); ?>"],
            product_sku: ["<?php echo $_product->getSku(); ?>"],
            product_name: ["<?php echo $_product->getName(); ?>"],
            product_brand: ["<?php echo $_product->getBrand(); ?>"],
            product_category: ["<?php echo $_category ? $_category->getName() : 'no_category'; ?>"],
            <?php if ($_product->getSpecialPrice()!='') echo 'product_unit_price: ["'.number_format($_product->getSpecialPrice(),2) .'"],'; ?>
            product_list_price: ["<?php echo number_format($_product->getPrice(),2); ?>"]
    };
</script>
